### ISSUE TITLE
Error trying to install this cartridge

### ISSUE THREAD

**Issue by coreydaley** [jhadvig/openshift-pascal-cartridge#2]
I get the following error trying to install this cartridge.  Is it working for you? Or is this in a development stage and non-working at the moment?

cdaley-redhat:~ cdaley$ rhc app create freepascal2 https://cartreflect-claytondev.rhcloud.com/reflect?github=jhadvig/openshift-pascal-cartridge
The cartridge
'https://cartreflect-claytondev.rhcloud.com/reflect?github=jhadvig/openshift-pascal-cartridge' will
be downloaded and installed
## Application Options

Domain:     cdaley
Cartridges: https://cartreflect-claytondev.rhcloud.com/reflect?github=jhadvig/openshift-pascal-cartridge
Gear Size:  default
Scaling:    no

Creating application 'freepascal2' ... 
/bin/sh: /var/lib/openshift/5391fb775973caacb300047c/pascal/bin/setup: Permission denied

**Comment by jhadvig** [comment]
Hi @developercorey,
no unfortunatelly there are still a few things that need to be done to have the cart. up and running.
I shall get to do it this week.
Thanks for issue.

**Comment by coreydaley** [comment]
Closing due to age.
